import Header from './components/Header'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='container bg-slate-500 w-full md:w-max-[90%] mx-auto '>
        <Header/>
        {children}
        </body>
    </html>
  )
}
